print('Nhap cac canh cua tam giac')
a=float(input("nhap canh a: "))
b=float(input("nhapcanh b: "))
c=float(input("nhap canh c: "))
print('kiem tra 3 canh co phai la tam giac')
answer=(a + b > c) and (a + c > b) and (b + c > a) and (a!=0) and (b!=0) and (c!=0)
print(answer)
print('Kiem tra tam giac deu')
answer = (a==b==c) and (a!=0) and (b!=0) and (c!=0)
print(answer)
print('kiem tra tam giac can')
answer= ((a==b) or (a==c) or (b==c)) and ((a!=0) and (b!=0) and (c!=0))
print(answer)
print('Kiem tra tam giac vuong')
answer = ((a*a == b*b + c*c) or (b*b == a*a + c*c) or (c*c == a*a + b*b))  and ((a!=0) and (b!=0) and (c!=0))
print(answer)